#!/bin/bash

bash evaluate_model.sh kasteren_house_a/reduced/word2vec_retrofitted_activities/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_retrofitted_locations/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_retrofitted_activities_locations/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_retrofitted_activities_from_data/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_retrofitted_locations_from_data/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_retrofitted_activities_locations_from_data/window_1_iterations_5_embedding_size_50 test 10

bash evaluate_model.sh kasteren_house_b/word2vec_retrofitted_activities/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_retrofitted_locations/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_retrofitted_activities_locations/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_retrofitted_activities_from_data/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_retrofitted_locations_from_data/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_retrofitted_activities_locations_from_data/window_1_iterations_5_embedding_size_50 test 10

bash evaluate_model.sh kasteren_house_c/word2vec_retrofitted_activities/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_retrofitted_locations/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_retrofitted_activities_locations/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_retrofitted_activities_from_data/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_retrofitted_locations_from_data/window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_retrofitted_activities_locations_from_data/window_1_iterations_5_embedding_size_50 test 10

bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_retrofitted_activities/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_retrofitted_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_retrofitted_activities_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_retrofitted_activities_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_retrofitted_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_retrofitted_activities_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10

bash evaluate_model.sh kasteren_house_b/word2vec_context_retrofitted_activities/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_context_retrofitted_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_context_retrofitted_activities_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_context_retrofitted_activities_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_context_retrofitted_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_b/word2vec_context_retrofitted_activities_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10

bash evaluate_model.sh kasteren_house_c/word2vec_context_retrofitted_activities/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_context_retrofitted_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_context_retrofitted_activities_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_context_retrofitted_activities_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_context_retrofitted_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10
bash evaluate_model.sh kasteren_house_c/word2vec_context_retrofitted_activities_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 10

bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_desc_retrofitted_activities/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_desc_retrofitted_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_desc_retrofitted_activities_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_desc_retrofitted_activities_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_desc_retrofitted_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_a/reduced/word2vec_context_desc_retrofitted_activities_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4

bash evaluate_model.sh kasteren_house_b/word2vec_context_desc_retrofitted_activities/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_b/word2vec_context_desc_retrofitted_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_b/word2vec_context_desc_retrofitted_activities_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_b/word2vec_context_desc_retrofitted_activities_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_b/word2vec_context_desc_retrofitted_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_b/word2vec_context_desc_retrofitted_activities_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4

bash evaluate_model.sh kasteren_house_c/word2vec_context_desc_retrofitted_activities/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_c/word2vec_context_desc_retrofitted_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_c/word2vec_context_desc_retrofitted_activities_locations/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_c/word2vec_context_desc_retrofitted_activities_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_c/word2vec_context_desc_retrofitted_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4
bash evaluate_model.sh kasteren_house_c/word2vec_context_desc_retrofitted_activities_locations_from_data/context_window_1_window_1_iterations_5_embedding_size_50 test 4